package actions

import (
	"fmt"
	"net/http"

	"github.com/gobuffalo/buffalo"
	"github.com/gobuffalo/pop/v6"
	"github.com/gobuffalo/x/responder"

	"webapp/models"
)

// This file is generated by Buffalo. It offers a basic structure for
// adding, editing and deleting a page. If your model is more
// complex or you need more than the basic implementation you need to
// edit this file.

// Following naming logic is implemented in Buffalo:
// Model: Singular (Material)
// DB Table: Plural (materials)
// Resource: Plural (Materials)
// Path: Plural (/materials)
// View Template Folder: Plural (/templates/materials/)

// MaterialsResource is the resource for the Material model
type MaterialsResource struct {
	buffalo.Resource
}

// List gets all Materials. This function is mapped to the path
// GET /materials
func (v MaterialsResource) List(c buffalo.Context) error {
	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return fmt.Errorf("no transaction found")
	}

	materials := &models.Materials{}

	// Paginate results. Params "page" and "per_page" control pagination.
	// Default values are "page=1" and "per_page=20".
	q := tx.PaginateFromParams(c.Params())

	// Retrieve all Materials from the DB
	if err := q.All(materials); err != nil {
		return err
	}

	return responder.Wants("html", func(c buffalo.Context) error {
		// Add the paginator to the context so it can be used in the template.
		c.Set("pagination", q.Paginator)

		c.Set("materials", materials)
		return c.Render(http.StatusOK, r.HTML("materials/index.plush.html"))
	}).Wants("json", func(c buffalo.Context) error {
		return c.Render(200, r.JSON(materials))
	}).Wants("xml", func(c buffalo.Context) error {
		return c.Render(200, r.XML(materials))
	}).Respond(c)
}

// Show gets the data for one Material. This function is mapped to
// the path GET /materials/{material_id}
func (v MaterialsResource) Show(c buffalo.Context) error {
	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return fmt.Errorf("no transaction found")
	}

	// Allocate an empty Material
	material := &models.Material{}

	// To find the Material the parameter material_id is used.
	if err := tx.Find(material, c.Param("material_id")); err != nil {
		return c.Error(http.StatusNotFound, err)
	}

	return responder.Wants("html", func(c buffalo.Context) error {
		c.Set("material", material)

		return c.Render(http.StatusOK, r.HTML("materials/show.plush.html"))
	}).Wants("json", func(c buffalo.Context) error {
		return c.Render(200, r.JSON(material))
	}).Wants("xml", func(c buffalo.Context) error {
		return c.Render(200, r.XML(material))
	}).Respond(c)
}

// Create adds a Material to the DB. This function is mapped to the
// path POST /materials
func (v MaterialsResource) Create(c buffalo.Context) error {
	// Allocate an empty Material
	material := &models.Material{}

	// Bind material to the html form elements
	if err := c.Bind(material); err != nil {
		return err
	}

	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return fmt.Errorf("no transaction found")
	}

	// Validate the data from the html form
	verrs, err := tx.ValidateAndCreate(material)
	if err != nil {
		return err
	}

	if verrs.HasAny() {
		return responder.Wants("html", func(c buffalo.Context) error {
			// Make the errors available inside the html template
			c.Set("errors", verrs)

			// Render again the new.html template that the user can
			// correct the input.
			c.Set("material", material)

			return c.Render(http.StatusUnprocessableEntity, r.HTML("materials/new.plush.html"))
		}).Wants("json", func(c buffalo.Context) error {
			return c.Render(http.StatusUnprocessableEntity, r.JSON(verrs))
		}).Wants("xml", func(c buffalo.Context) error {
			return c.Render(http.StatusUnprocessableEntity, r.XML(verrs))
		}).Respond(c)
	}

	return responder.Wants("html", func(c buffalo.Context) error {
		// If there are no errors set a success message
		c.Flash().Add("success", T.Translate(c, "material.created.success"))

		// and redirect to the show page
		return c.Redirect(http.StatusSeeOther, "/materials/%v", material.ID)
	}).Wants("json", func(c buffalo.Context) error {
		return c.Render(http.StatusCreated, r.JSON(material))
	}).Wants("xml", func(c buffalo.Context) error {
		return c.Render(http.StatusCreated, r.XML(material))
	}).Respond(c)
}

// Update changes a Material in the DB. This function is mapped to
// the path PUT /materials/{material_id}
func (v MaterialsResource) Update(c buffalo.Context) error {
	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return fmt.Errorf("no transaction found")
	}

	// Allocate an empty Material
	material := &models.Material{}

	if err := tx.Find(material, c.Param("material_id")); err != nil {
		return c.Error(http.StatusNotFound, err)
	}

	// Bind Material to the html form elements
	if err := c.Bind(material); err != nil {
		return err
	}

	verrs, err := tx.ValidateAndUpdate(material)
	if err != nil {
		return err
	}

	if verrs.HasAny() {
		return responder.Wants("html", func(c buffalo.Context) error {
			// Make the errors available inside the html template
			c.Set("errors", verrs)

			// Render again the edit.html template that the user can
			// correct the input.
			c.Set("material", material)

			return c.Render(http.StatusUnprocessableEntity, r.HTML("materials/edit.plush.html"))
		}).Wants("json", func(c buffalo.Context) error {
			return c.Render(http.StatusUnprocessableEntity, r.JSON(verrs))
		}).Wants("xml", func(c buffalo.Context) error {
			return c.Render(http.StatusUnprocessableEntity, r.XML(verrs))
		}).Respond(c)
	}

	return responder.Wants("html", func(c buffalo.Context) error {
		// If there are no errors set a success message
		c.Flash().Add("success", T.Translate(c, "material.updated.success"))

		// and redirect to the show page
		return c.Redirect(http.StatusSeeOther, "/materials/%v", material.ID)
	}).Wants("json", func(c buffalo.Context) error {
		return c.Render(http.StatusOK, r.JSON(material))
	}).Wants("xml", func(c buffalo.Context) error {
		return c.Render(http.StatusOK, r.XML(material))
	}).Respond(c)
}

// Destroy deletes a Material from the DB. This function is mapped
// to the path DELETE /materials/{material_id}
func (v MaterialsResource) Destroy(c buffalo.Context) error {
	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return fmt.Errorf("no transaction found")
	}

	// Allocate an empty Material
	material := &models.Material{}

	// To find the Material the parameter material_id is used.
	if err := tx.Find(material, c.Param("material_id")); err != nil {
		return c.Error(http.StatusNotFound, err)
	}

	if err := tx.Destroy(material); err != nil {
		return err
	}

	return responder.Wants("html", func(c buffalo.Context) error {
		// If there are no errors set a flash message
		c.Flash().Add("success", T.Translate(c, "material.destroyed.success"))

		// Redirect to the index page
		return c.Redirect(http.StatusSeeOther, "/materials")
	}).Wants("json", func(c buffalo.Context) error {
		return c.Render(http.StatusOK, r.JSON(material))
	}).Wants("xml", func(c buffalo.Context) error {
		return c.Render(http.StatusOK, r.XML(material))
	}).Respond(c)
}
