package actions

import (
	"fmt"
	"net/http"

	"github.com/gobuffalo/buffalo"
	"github.com/gobuffalo/pop/v6"
	"github.com/gobuffalo/x/responder"

	"webapp/models"
)

// This file is generated by Buffalo. It offers a basic structure for
// adding, editing and deleting a page. If your model is more
// complex or you need more than the basic implementation you need to
// edit this file.

// Following naming logic is implemented in Buffalo:
// Model: Singular (ServiceCall)
// DB Table: Plural (service_calls)
// Resource: Plural (ServiceCalls)
// Path: Plural (/service_calls)
// View Template Folder: Plural (/templates/service_calls/)

// ServiceCallsResource is the resource for the ServiceCall model
type ServiceCallsResource struct {
	buffalo.Resource
}

// List gets all ServiceCalls. This function is mapped to the path
// GET /service_calls
func (v ServiceCallsResource) List(c buffalo.Context) error {
	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return fmt.Errorf("no transaction found")
	}

	serviceCalls := &models.ServiceCalls{}

	// Paginate results. Params "page" and "per_page" control pagination.
	// Default values are "page=1" and "per_page=20".
	q := tx.PaginateFromParams(c.Params())

	// Retrieve all ServiceCalls from the DB
	if err := q.All(serviceCalls); err != nil {
		return err
	}

	return responder.Wants("html", func(c buffalo.Context) error {
		// Add the paginator to the context so it can be used in the template.
		c.Set("pagination", q.Paginator)

		c.Set("serviceCalls", serviceCalls)
		return c.Render(http.StatusOK, r.HTML("service_calls/index.plush.html"))
	}).Wants("json", func(c buffalo.Context) error {
		return c.Render(200, r.JSON(serviceCalls))
	}).Wants("xml", func(c buffalo.Context) error {
		return c.Render(200, r.XML(serviceCalls))
	}).Respond(c)
}

// Show gets the data for one ServiceCall. This function is mapped to
// the path GET /service_calls/{service_call_id}
func (v ServiceCallsResource) Show(c buffalo.Context) error {
	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return fmt.Errorf("no transaction found")
	}

	// Allocate an empty ServiceCall
	serviceCall := &models.ServiceCall{}

	// To find the ServiceCall the parameter service_call_id is used.
	if err := tx.Find(serviceCall, c.Param("service_call_id")); err != nil {
		return c.Error(http.StatusNotFound, err)
	}

	return responder.Wants("html", func(c buffalo.Context) error {
		c.Set("serviceCall", serviceCall)

		return c.Render(http.StatusOK, r.HTML("service_calls/show.plush.html"))
	}).Wants("json", func(c buffalo.Context) error {
		return c.Render(200, r.JSON(serviceCall))
	}).Wants("xml", func(c buffalo.Context) error {
		return c.Render(200, r.XML(serviceCall))
	}).Respond(c)
}

// Create adds a ServiceCall to the DB. This function is mapped to the
// path POST /service_calls
func (v ServiceCallsResource) Create(c buffalo.Context) error {
	// Allocate an empty ServiceCall
	serviceCall := &models.ServiceCall{}

	// Bind serviceCall to the html form elements
	if err := c.Bind(serviceCall); err != nil {
		return err
	}

	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return fmt.Errorf("no transaction found")
	}

	// Validate the data from the html form
	verrs, err := tx.ValidateAndCreate(serviceCall)
	if err != nil {
		return err
	}

	if verrs.HasAny() {
		return responder.Wants("html", func(c buffalo.Context) error {
			// Make the errors available inside the html template
			c.Set("errors", verrs)

			// Render again the new.html template that the user can
			// correct the input.
			c.Set("serviceCall", serviceCall)

			return c.Render(http.StatusUnprocessableEntity, r.HTML("service_calls/new.plush.html"))
		}).Wants("json", func(c buffalo.Context) error {
			return c.Render(http.StatusUnprocessableEntity, r.JSON(verrs))
		}).Wants("xml", func(c buffalo.Context) error {
			return c.Render(http.StatusUnprocessableEntity, r.XML(verrs))
		}).Respond(c)
	}

	return responder.Wants("html", func(c buffalo.Context) error {
		// If there are no errors set a success message
		c.Flash().Add("success", T.Translate(c, "serviceCall.created.success"))

		// and redirect to the show page
		return c.Redirect(http.StatusSeeOther, "/service_calls/%v", serviceCall.ID)
	}).Wants("json", func(c buffalo.Context) error {
		return c.Render(http.StatusCreated, r.JSON(serviceCall))
	}).Wants("xml", func(c buffalo.Context) error {
		return c.Render(http.StatusCreated, r.XML(serviceCall))
	}).Respond(c)
}

// Update changes a ServiceCall in the DB. This function is mapped to
// the path PUT /service_calls/{service_call_id}
func (v ServiceCallsResource) Update(c buffalo.Context) error {
	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return fmt.Errorf("no transaction found")
	}

	// Allocate an empty ServiceCall
	serviceCall := &models.ServiceCall{}

	if err := tx.Find(serviceCall, c.Param("service_call_id")); err != nil {
		return c.Error(http.StatusNotFound, err)
	}

	// Bind ServiceCall to the html form elements
	if err := c.Bind(serviceCall); err != nil {
		return err
	}

	verrs, err := tx.ValidateAndUpdate(serviceCall)
	if err != nil {
		return err
	}

	if verrs.HasAny() {
		return responder.Wants("html", func(c buffalo.Context) error {
			// Make the errors available inside the html template
			c.Set("errors", verrs)

			// Render again the edit.html template that the user can
			// correct the input.
			c.Set("serviceCall", serviceCall)

			return c.Render(http.StatusUnprocessableEntity, r.HTML("service_calls/edit.plush.html"))
		}).Wants("json", func(c buffalo.Context) error {
			return c.Render(http.StatusUnprocessableEntity, r.JSON(verrs))
		}).Wants("xml", func(c buffalo.Context) error {
			return c.Render(http.StatusUnprocessableEntity, r.XML(verrs))
		}).Respond(c)
	}

	return responder.Wants("html", func(c buffalo.Context) error {
		// If there are no errors set a success message
		c.Flash().Add("success", T.Translate(c, "serviceCall.updated.success"))

		// and redirect to the show page
		return c.Redirect(http.StatusSeeOther, "/service_calls/%v", serviceCall.ID)
	}).Wants("json", func(c buffalo.Context) error {
		return c.Render(http.StatusOK, r.JSON(serviceCall))
	}).Wants("xml", func(c buffalo.Context) error {
		return c.Render(http.StatusOK, r.XML(serviceCall))
	}).Respond(c)
}

// Destroy deletes a ServiceCall from the DB. This function is mapped
// to the path DELETE /service_calls/{service_call_id}
func (v ServiceCallsResource) Destroy(c buffalo.Context) error {
	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return fmt.Errorf("no transaction found")
	}

	// Allocate an empty ServiceCall
	serviceCall := &models.ServiceCall{}

	// To find the ServiceCall the parameter service_call_id is used.
	if err := tx.Find(serviceCall, c.Param("service_call_id")); err != nil {
		return c.Error(http.StatusNotFound, err)
	}

	if err := tx.Destroy(serviceCall); err != nil {
		return err
	}

	return responder.Wants("html", func(c buffalo.Context) error {
		// If there are no errors set a flash message
		c.Flash().Add("success", T.Translate(c, "serviceCall.destroyed.success"))

		// Redirect to the index page
		return c.Redirect(http.StatusSeeOther, "/service_calls")
	}).Wants("json", func(c buffalo.Context) error {
		return c.Render(http.StatusOK, r.JSON(serviceCall))
	}).Wants("xml", func(c buffalo.Context) error {
		return c.Render(http.StatusOK, r.XML(serviceCall))
	}).Respond(c)
}
